language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"

script:
- cd Code
- python setup_cython.py build_ext --inplace
- nosetests -s -v -w tests
